-- Fetch Group, Nested-Group, Manager, & Member data
SELECT dig.GROUP_ID
	, dig.LDAP_HOST
	, dig.LDAP_OU
	, dig.GROUP_NAME
    , REGEXP_SUBSTR(digm.MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP
	, dig.PRIMARY_MANAGER_SSO AS GM_SSO
	--, TRIM (',' FROM iu.FIRST_NAME || ' ' || iu.MIDDLE_NAME  || ', ' || iu.LAST_NAME) AS GM_NAME
	, iu.EMAIL_DISPLAY_NAME AS GM_EMAIL_DISP
    --, iu.EMAIL_ADDRESS AS GM_EMAIL_ADD
    , iu.PERSON_STATUS AS GM_STATUS
    , iu.PERSON_TYPE AS GM_TYPE
    , iu.JOB_TITLE AS GM_TITLE
    , iu.JOB_FUNCTION AS GM_FUNC
    --, iu.SSO_EXPIRATION_DATE AS GM_EXP_DATE
    --, iu.LAST_UPDATE_DATE AS GM_UPD_DATE
    --, iu.EFFECTIVE_DATE AS GM_EFF_DATE
    , iu.INDUSTRY_FOCUS_NAME AS GM_BU
    , iu.BUSINESS_SEGMENT AS GM_BU_SEG
    --, iu.COMPANYNAME AS GM_COM
    , iu.DEPARTMENT_NAME AS GM_DEP
	, ium.PERSON_NUM_SSO AS GU_SSO
	--, TRIM (',' FROM ium.FIRST_NAME || ' ' || ium.MIDDLE_NAME  || ', ' || ium.LAST_NAME) AS GU_NAME
	, ium.EMAIL_DISPLAY_NAME AS GU_EMAIL_DISP
    --, ium.EMAIL_ADDRESS AS GU_EMAIL_ADD
    , ium.PERSON_STATUS AS GU_STATUS
    , ium.PERSON_TYPE AS GU_TYPE
    , ium.JOB_TITLE	AS GU_TITLE
    , ium.JOB_FUNCTION AS GU_FUNC
    --, ium.SSO_EXPIRATION_DATE AS GU_EXP_DATE
    --, ium.LAST_UPDATE_DATE AS GU_UPD_DATE
    --, ium.EFFECTIVE_DATE AS GU_EFF_DATE
    , ium.INDUSTRY_FOCUS_NAME AS GU_BU
    , ium.BUSINESS_SEGMENT AS GU_BU_SEG
    , ium.DEPARTMENT_NAME AS GU_DEP
FROM IDM.DW_IDM_GROUP dig 
JOIN IDM.IDM_USER iu ON dig.PRIMARY_MANAGER_SSO = iu.PERSON_NUM_SSO	
JOIN IDM.DW_IDM_GROUP_MEMBER digm ON dig.GROUP_ID = digm.GROUP_ID
JOIN IDM.IDM_USER ium ON digm.MEMBER = ium.PERSON_NUM_SSO	
	WHERE dig.GROUP_NAME LIKE '@GE Cloud%' 
		-- Filter for Commercial & GovCloud DLs which ends to 12 digits AWS Account ID
		OR ( dig.GROUP_NAME LIKE '@GE AWS_%' AND REGEXP_LIKE(dig.GROUP_NAME, '[0-9]{12}$') )
		OR ( dig.GROUP_NAME LIKE '@GE GOVAWS_%' AND REGEXP_LIKE(dig.GROUP_NAME, '[0-9]{12}$') )
	ORDER BY dig.GROUP_NAME ASC, dig.GROUP_ID ASC

-- SOX Only - Fetch Group, Nested-Group, Manager, & Member data
SELECT 
    dig.GROUP_ID, 
	dig.LDAP_HOST, 
	dig.LDAP_OU, 
	dig.GROUP_NAME, 
    REGEXP_SUBSTR(digm.MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP, 
	dig.PRIMARY_MANAGER_SSO AS GM_SSO, 
	iu.EMAIL_DISPLAY_NAME AS GM_EMAIL_DISP, 
    iu.PERSON_STATUS AS GM_STATUS, 
    iu.PERSON_TYPE AS GM_TYPE, 
    iu.JOB_TITLE AS GM_TITLE, 
    iu.JOB_FUNCTION AS GM_FUNC, 
    iu.INDUSTRY_FOCUS_NAME AS GM_BU, 
    iu.BUSINESS_SEGMENT AS GM_BU_SEG, 
    iu.DEPARTMENT_NAME AS GM_DEP, 
	ium.PERSON_NUM_SSO AS GU_SSO, 
	ium.EMAIL_DISPLAY_NAME AS GU_EMAIL_DISP, 
    ium.PERSON_STATUS AS GU_STATUS, 
    ium.PERSON_TYPE AS GU_TYPE, 
    ium.JOB_TITLE AS GU_TITLE, 
    ium.JOB_FUNCTION AS GU_FUNC, 
    ium.INDUSTRY_FOCUS_NAME AS GU_BU, 
    ium.BUSINESS_SEGMENT AS GU_BU_SEG, 
    ium.DEPARTMENT_NAME AS GU_DEP
FROM IDM.DW_IDM_GROUP dig 
JOIN IDM.IDM_USER iu ON dig.PRIMARY_MANAGER_SSO = iu.PERSON_NUM_SSO	
JOIN IDM.DW_IDM_GROUP_MEMBER digm ON dig.GROUP_ID = digm.GROUP_ID
JOIN IDM.IDM_USER ium ON digm.MEMBER = ium.PERSON_NUM_SSO	
	WHERE ( dig.GROUP_NAME LIKE '@GE Cloud%' 
		-- Filter for Commercial & GovCloud DLs which ends to 12 digits AWS Account ID
		OR ( dig.GROUP_NAME LIKE '@GE AWS_%' AND REGEXP_LIKE(dig.GROUP_NAME, '[0-9]{12}$') )
		OR ( dig.GROUP_NAME LIKE '@GE GOVAWS_%' AND REGEXP_LIKE(dig.GROUP_NAME, '[0-9]{12}$') )
    ) AND ( dig.GROUP_NAME LIKE '%141111311552%'
        OR dig.GROUP_NAME LIKE '%188894168332%'
        OR dig.GROUP_NAME LIKE '%207755114178%'
        OR dig.GROUP_NAME LIKE '%264560008398%'
        OR dig.GROUP_NAME LIKE '%277688789493%'
        OR dig.GROUP_NAME LIKE '%376079469356%'
        OR dig.GROUP_NAME LIKE '%432403552778%'
        OR dig.GROUP_NAME LIKE '%504948279284%'
        OR dig.GROUP_NAME LIKE '%556003251088%'
        OR dig.GROUP_NAME LIKE '%589623221417%'
        OR dig.GROUP_NAME LIKE '%736489861251%'
        OR dig.GROUP_NAME LIKE '%737859062117%'
        OR dig.GROUP_NAME LIKE '%020202940623%'
        OR dig.GROUP_NAME LIKE '%147947222044%'
        OR dig.GROUP_NAME LIKE '%330271845325%'
        OR dig.GROUP_NAME LIKE '%610798319622%'
        OR dig.GROUP_NAME LIKE '%715477192348%'
        OR dig.GROUP_NAME LIKE '%896094434431%'
    )
	ORDER BY dig.GROUP_NAME ASC, dig.GROUP_ID ASC

-- All SOX DL
SELECT 
    G.GROUP_ID, 
    G.LDAP_HOST, 
    G.LDAP_OU, 
    G.GROUP_NAME, 
    REGEXP_SUBSTR(M.MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP, 
    G.PRIMARY_MANAGER_SSO AS GM_SSO, 
    GM.EMAIL_DISPLAY_NAME AS GM_EMAIL_DISP, 
    GM.PERSON_STATUS AS GM_STATUS, 
    GM.PERSON_TYPE AS GM_TYPE, 
    GM.JOB_TITLE AS GM_TITLE, 
    GM.JOB_FUNCTION AS GM_FUNC, 
    GM.INDUSTRY_FOCUS_NAME AS GM_BU, 
    GM.BUSINESS_SEGMENT AS GM_BU_SEG, 
    GM.DEPARTMENT_NAME AS GM_DEP, 
    GU.PERSON_NUM_SSO AS GU_SSO, 
    GU.EMAIL_DISPLAY_NAME AS GU_EMAIL_DISP, 
    GU.PERSON_STATUS AS GU_STATUS, 
    GU.PERSON_TYPE AS GU_TYPE, 
    GU.JOB_TITLE AS GU_TITLE, 
    GU.JOB_FUNCTION AS GU_FUNC, 
    GU.INDUSTRY_FOCUS_NAME AS GU_BU, 
    GU.BUSINESS_SEGMENT AS GU_BU_SEG, 
    GU.DEPARTMENT_NAME AS GU_DEP
FROM IDM.DW_IDM_GROUP G 
JOIN IDM.IDM_USER GM ON G.PRIMARY_MANAGER_SSO = GM.PERSON_NUM_SSO	
JOIN IDM.DW_IDM_GROUP_MEMBER M ON G.GROUP_ID = M.GROUP_ID
JOIN IDM.IDM_USER GU ON M.MEMBER = GU.PERSON_NUM_SSO 
WHERE ( G.GROUP_NAME LIKE '@GE Cloud%' 
    -- Filter for Commercial & GovCloud DLs which ends to 12 Gits AWS Account ID
    OR ( G.GROUP_NAME LIKE '@GE AWS_%' AND REGEXP_LIKE(G.GROUP_NAME, '[0-9]{12}$') )
    OR ( G.GROUP_NAME LIKE '@GE GOVAWS_%' AND REGEXP_LIKE(G.GROUP_NAME, '[0-9]{12}$') )
) AND ( G.GROUP_NAME LIKE '%141111311552%'
    OR G.GROUP_NAME LIKE '%188894168332%'
    OR G.GROUP_NAME LIKE '%207755114178%'
    OR G.GROUP_NAME LIKE '%264560008398%'
    OR G.GROUP_NAME LIKE '%277688789493%'
    OR G.GROUP_NAME LIKE '%376079469356%'
    OR G.GROUP_NAME LIKE '%432403552778%'
    OR G.GROUP_NAME LIKE '%504948279284%'
    OR G.GROUP_NAME LIKE '%556003251088%'
    OR G.GROUP_NAME LIKE '%589623221417%'
    OR G.GROUP_NAME LIKE '%736489861251%'
    OR G.GROUP_NAME LIKE '%737859062117%'
    OR G.GROUP_NAME LIKE '%020202940623%'
    OR G.GROUP_NAME LIKE '%147947222044%'
    OR G.GROUP_NAME LIKE '%330271845325%'
    OR G.GROUP_NAME LIKE '%610798319622%'
    OR G.GROUP_NAME LIKE '%715477192348%'
    OR G.GROUP_NAME LIKE '%896094434431%'
) 
ORDER BY G.GROUP_NAME ASC, G.GROUP_ID ASC, G.PRIMARY_MANAGER_SSO ASC, GU.EMAIL_DISPLAY_NAME ASC

-- Filter GROUP_ID, GROUP_NAME, SSO
-- '@GE AWS_cs/p-jump-engineering_58962322141
SELECT 
    G.GROUP_ID, 
    G.LDAP_HOST, 
    G.LDAP_OU, 
    G.GROUP_NAME, 
    REGEXP_SUBSTR(M.MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP, 
    G.PRIMARY_MANAGER_SSO AS GM_SSO, 
    GM.EMAIL_DISPLAY_NAME AS GM_EMAIL_DISP, 
    GM.PERSON_STATUS AS GM_STATUS, 
    GM.PERSON_TYPE AS GM_TYPE, 
    GM.JOB_TITLE AS GM_TITLE, 
    GM.JOB_FUNCTION AS GM_FUNC, 
    GM.INDUSTRY_FOCUS_NAME AS GM_BU, 
    GM.BUSINESS_SEGMENT AS GM_BU_SEG, 
    GM.DEPARTMENT_NAME AS GM_DEP, 
    GU.PERSON_NUM_SSO AS GU_SSO, 
    GU.EMAIL_DISPLAY_NAME AS GU_EMAIL_DISP, 
    GU.PERSON_STATUS AS GU_STATUS, 
    GU.PERSON_TYPE AS GU_TYPE, 
    GU.JOB_TITLE AS GU_TITLE, 
    GU.JOB_FUNCTION AS GU_FUNC, 
    GU.INDUSTRY_FOCUS_NAME AS GU_BU, 
    GU.BUSINESS_SEGMENT AS GU_BU_SEG, 
    GU.DEPARTMENT_NAME AS GU_DEP
FROM IDM.DW_IDM_GROUP G 
JOIN IDM.IDM_USER GM ON G.PRIMARY_MANAGER_SSO = GM.PERSON_NUM_SSO	
JOIN IDM.DW_IDM_GROUP_MEMBER M ON G.GROUP_ID = M.GROUP_ID
JOIN IDM.IDM_USER GU ON M.MEMBER = GU.PERSON_NUM_SSO 
WHERE G.GROUP_ID = '200007062'
	OR G.GROUP_NAME = '200007062'
	OR M.MEMBER = '200007062'
ORDER BY G.GROUP_NAME ASC, G.GROUP_ID ASC, G.PRIMARY_MANAGER_SSO ASC, GU.EMAIL_DISPLAY_NAME ASC

-- '@GE AWS_cs/p-jump-engineering_58962322141
-- '200007062'
-- 