--DW_GROUPS_HEALTHCARE_V		
SELECT GROUP_ID, LDAP_HOST, LDAP_OU, GROUP_NAME, PRIMARY_MANAGER_SSO, ATTR_GEAPPNAME, ATTR_GECPASECURITYGROUP, ATTR_GECPAGROUPECSTATUS
FROM IDM.DW_IDM_GROUP G
JOIN IDM_USER U ON G.PRIMARY_MANAGER_SSO = U.PERSON_NUM_SSO
WHERE U.INDUSTRY_FOCUS_NAME = 'GE Healthcare'

--DW_GROUP_AUDIT_DATA_POWER_V
SELECT "ID", "GROUP_NAME", "GROUP_ID", "PRIMARY_MANAGER_SSO", "PRIMARY_MANAGER_BUSINESS", "AUDIT_EVENT_CREATED", "SOURCE", "ACTION", "INSTANCE", "ATTRIBUTE_NAME", "ATTRIBUTES" 
FROM IDM.DW_GROUP_AUDIT_DATA
WHERE PRIMARY_MANAGER_BUSINESS IN ('GE Power', 'GE Power Portfolio', 'GE Gas Power')

--DW_GROUP_AVIATION_V
SELECT G."GROUP_ID", G."LDAP_HOST", G."LDAP_OU", G."GROUP_NAME", G."PRIMARY_MANAGER_SSO", G."ATTR_GEAPPNAME", G."ATTR_GECPASECURITYGROUP", G."ATTR_GECPAGROUPECSTATUS"
FROM IDM.DW_IDM_GROUP G
LEFT JOIN IDM.IDM_user U ON G.PRIMARY_MANAGER_SSO = U.PERSON_NUM_SSO
WHERE U.INDUSTRY_FOCUS_ID IS NOT NULL
AND U.INDUSTRY_FOCUS_ID = '1178320'

--DW_GROUP_MANAGER_AVIATION_V		
SELECT GMGR."GROUP_ID", GMGR."MANAGER", U.FIRST_NAME, U.LAST_NAME, U.EMAIL_ADDRESS, U.MANAGER_PERSON_NUM, U.PERSON_STATUS
FROM IDM.DW_IDM_GROUP_MANAGER GMGR
JOIN IDM.DW_GROUP_AVIATION_V G ON GMGR.GROUP_ID = G.GROUP_ID -- DW_GROUP_AVIATION_G only presents GROUPS with Primary Managers in AVIATION
LEFT JOIN IDM.IDM_USER U ON GMGR.MANAGER = U.PERSON_NUM_SSO

--DW_GROUP_MANAGER_VERNOVA_V		
SELECT GMGR."GROUP_ID", GMGR."MANAGER", U.FIRST_NAME, U.LAST_NAME, U.EMAIL_ADDRESS, U.MANAGER_PERSON_NUM, U.PERSON_STATUS
FROM IDM.DW_IDM_GROUP_MANAGER GMGR
JOIN IDM.DW_GROUP_VERNOVA_V G ON GMGR.GROUP_ID = G.GROUP_ID -- DW_GROUP_VERNOVA_G only presents GROUPS with Primary Managers in Vernova
LEFT JOIN IDM.IDM_USER U ON GMGR.MANAGER = U.PERSON_NUM_SSO

--DW_GROUP_MEMBER_AVIATION_V		
SELECT GM."GROUP_ID", GM."MEMBER", U.FIRST_NAME, U.LAST_NAME, U.EMAIL_ADDRESS, U.MANAGER_PERSON_NUM, U.PERSON_STATUS
FROM IDM.DW_IDM_GROUP_MEMBER GM
JOIN IDM.DW_GROUP_AVIATION_V G ON GM.GROUP_ID = G.GROUP_ID -- DW_GROUP_AVIATION_G only presents GROUPS with Primary Managers in AVIATION
LEFT JOIN IDM.IDM_USER U ON GM.MEMBER=U.PERSON_NUM_SSO

--DW_GROUP_MEMBER_VERNOVA_V		
SELECT GM."GROUP_ID", GM."MEMBER", U.FIRST_NAME, U.LAST_NAME, U.EMAIL_ADDRESS, U.MANAGER_PERSON_NUM, U.PERSON_STATUS
FROM IDM.DW_IDM_GROUP_MEMBER GM
JOIN IDM.DW_GROUP_VERNOVA_V G ON GM.GROUP_ID = G.GROUP_ID -- DW_GROUP_VERNOVA_G only presents GROUPS with Primary Managers in Vernova
LEFT JOIN IDM.IDM_USER U ON GM.MEMBER=U.PERSON_NUM_SSO

--DW_GROUP_OWNER_AVIATION_V		
SELECT GOWN."GROUP_ID", GOWN."OWNER", U.FIRST_NAME, U.LAST_NAME, U.EMAIL_ADDRESS, U.MANAGER_PERSON_NUM, U.PERSON_STATUS
FROM IDM.DW_IDM_GROUP_OWNER GOWN
JOIN IDM.DW_GROUP_AVIATION_V G ON GOWN.GROUP_ID = G.GROUP_ID -- DW_GROUP_AVIATION_G only presents GROUPS with Primary Managers in AVIATION
LEFT JOIN IDM.IDM_USER U ON GOWN.OWNER = U.PERSON_NUM_SSO

--DW_GROUP_OWNER_VERNOVA_V		
SELECT GOWN."GROUP_ID", GOWN."OWNER", U.FIRST_NAME, U.LAST_NAME, U.EMAIL_ADDRESS, U.MANAGER_PERSON_NUM, U.PERSON_STATUS
FROM IDM.DW_IDM_GROUP_OWNER GOWN
JOIN IDM.DW_GROUP_VERNOVA_V G ON GOWN.GROUP_ID = G.GROUP_ID -- DW_GROUP_VERNOVA_G only presents GROUPS with Primary Managers in Vernova
LEFT JOIN IDM.IDM_USER U ON GOWN.OWNER = U.PERSON_NUM_SSO

--DW_GROUP_VERNOVA_V		
SELECT G."GROUP_ID", G."LDAP_HOST", G."LDAP_OU", G."GROUP_NAME", G."PRIMARY_MANAGER_SSO", G."ATTR_GEAPPNAME", G."ATTR_GECPASECURITYGROUP", G."ATTR_GECPAGROUPECSTATUS"
FROM IDM.DW_IDM_GROUP G
LEFT JOIN IDM.IDM_USER U ON G.PRIMARY_MANAGER_SSO = U.PERSON_NUM_SSO
WHERE U.INDUSTRY_FOCUS_ID IS NOT NULL
    AND U.INDUSTRY_FOCUS_ID <> '1178477'
    AND U.INDUSTRY_FOCUS_ID <> '1178320'

--DW_USER_CHANGE_EVENTS_VERNOVA_V		
SELECT CL."IDM_USER_CHANGE_EVENT_ID", CL."PERSON_NUM_SSO", CL."EVENT_TYPE", CL."PERSON_STATUS", CL."PERSON_STATUS_OLD", CL."GEHRLOCATIONID", CL."GEHRLOCATIONID_OLD", CL."INDUSTRY_FOCUS_ID", CL."INDUSTRY_FOCUS_ID_OLD", CL."GEHRJOBID", CL."GEHRJOBID_OLD", CL."MANAGER_PERSON_NUM", CL."MANAGER_PERSON_NUM_OLD", CL."NEW_MANAGER_DETAILS", CL."OLD_MANAGER_DETAILS", CL."FIRST_NAME", CL."FIRST_NAME_OLD", CL."LAST_NAME", CL."LAST_NAME_OLD", CL."BUSINESS_SEGMENT_ID", CL."BUSINESS_SEGMENT_ID_OLD", CL."BUSINESS_SEGMENT_NAME", CL."BUSINESS_SEGMENT_NAME_OLD", CL."CITY", CL."CITY_OLD", CL."COUNTRY", CL."COUNTRY_OLD", CL."DEPARTMENT_NAME", CL."DEPARTMENT_NAME_OLD", CL."DIVISIONID", CL."DIVISIONID_OLD", CL."DIVISION_NAME", CL."DIVISION_NAME_OLD", CL."EMAIL_ADDRESS", CL."EMAIL_ADDRESS_OLD", CL."EMAIL_DISPLAY_NAME", CL."EMAIL_DISPLAY_NAME_OLD", CL."BU_NUMBER", CL."BU_NUMBER_OLD", CL."GRADE_BAND", CL."GRADE_BAND_OLD", CL."INDUSTRY_FOCUS_NAME", CL."INDUSTRY_FOCUS_NAME_OLD", CL."JOB_TITLE", CL."JOB_TITLE_OLD", CL."PERSON_TYPE", CL."PERSON_TYPE_OLD", CL."SSO_EXPIRATION_DATE", CL."SSO_EXPIRATION_DATE_OLD", CL."STATE", CL."STATE_OLD", CL."WORKER_TYPE", CL."WORKER_TYPE_OLD", CL."WORK_PHONE", CL."WORK_PHONE_OLD", CL."PROCESS_STATUS", CL."EXTN1", CL."EXTN2", CL."CREATION_DATE", CL."LAST_UPDATE_DATE", CL."MIDDLE_NAME", CL."MIDDLE_NAME_OLD", CL."GEHRASSIGNMENTSTATUS", CL."GEHRASSIGNMENTSTATUS_OLD", CL."GEHRPOSITIONID", CL."GEHRPOSITIONID_OLD"
FROM IDM.IDM_USER_CHANGE_EVENT_LOG CL
INNER JOIN IDM.DW_IDENTITY_VERNOVA_V I ON CL.PERSON_NUM_SSO = I.PERSON_NUM_SSO
WHERE CL.LAST_UPDATE_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -12)

-- CHANGE EVENTS FOR CoreTech
SELECT CL."IDM_USER_CHANGE_EVENT_ID", CL."PERSON_NUM_SSO", CL."EVENT_TYPE", CL."PERSON_STATUS", CL."PERSON_STATUS_OLD", CL."GEHRLOCATIONID", CL."GEHRLOCATIONID_OLD", CL."INDUSTRY_FOCUS_ID", CL."INDUSTRY_FOCUS_ID_OLD", CL."GEHRJOBID", CL."GEHRJOBID_OLD", CL."MANAGER_PERSON_NUM", CL."MANAGER_PERSON_NUM_OLD", CL."NEW_MANAGER_DETAILS", CL."OLD_MANAGER_DETAILS", CL."FIRST_NAME", CL."FIRST_NAME_OLD", CL."LAST_NAME", CL."LAST_NAME_OLD", CL."BUSINESS_SEGMENT_ID", CL."BUSINESS_SEGMENT_ID_OLD", CL."BUSINESS_SEGMENT_NAME", CL."BUSINESS_SEGMENT_NAME_OLD", CL."CITY", CL."CITY_OLD", CL."COUNTRY", CL."COUNTRY_OLD", CL."DEPARTMENT_NAME", CL."DEPARTMENT_NAME_OLD", CL."DIVISIONID", CL."DIVISIONID_OLD", CL."DIVISION_NAME", CL."DIVISION_NAME_OLD", CL."EMAIL_ADDRESS", CL."EMAIL_ADDRESS_OLD", CL."EMAIL_DISPLAY_NAME", CL."EMAIL_DISPLAY_NAME_OLD", CL."BU_NUMBER", CL."BU_NUMBER_OLD", CL."GRADE_BAND", CL."GRADE_BAND_OLD", CL."INDUSTRY_FOCUS_NAME", CL."INDUSTRY_FOCUS_NAME_OLD", CL."JOB_TITLE", CL."JOB_TITLE_OLD", CL."PERSON_TYPE", CL."PERSON_TYPE_OLD", CL."SSO_EXPIRATION_DATE", CL."SSO_EXPIRATION_DATE_OLD", CL."STATE", CL."STATE_OLD", CL."WORKER_TYPE", CL."WORKER_TYPE_OLD", CL."WORK_PHONE", CL."WORK_PHONE_OLD", CL."PROCESS_STATUS", CL."EXTN1", CL."EXTN2", CL."CREATION_DATE", CL."LAST_UPDATE_DATE", CL."MIDDLE_NAME", CL."MIDDLE_NAME_OLD", CL."GEHRASSIGNMENTSTATUS", CL."GEHRASSIGNMENTSTATUS_OLD", CL."GEHRPOSITIONID", CL."GEHRPOSITIONID_OLD"
FROM IDM.IDM_USER_CHANGE_EVENT_LOG CL
INNER JOIN IDM.DW_IDENTITY I ON CL.PERSON_NUM_SSO = I.IDENTITY 
WHERE CL.LAST_UPDATE_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -2)


--DW_USER_DELEGATION_VERNOVA_V		
SELECT SI.NAME, SI.FIRSTNAME, SI.LASTNAME, SI.EMAIL, EXTRACTVALUE(XMLTYPE(SI.PREFERENCES), '/Map/entry[@key="forward"]/@value') AS "Delegate SSO"
    , EST(EXTRACTVALUE(XMLTYPE(SI.PREFERENCES), '/Map/entry[@key="forwardStartDate"]/value/Date')) AS "Delegate Start Date"
    , EST(EXTRACTVALUE(XMLTYPE(SI.PREFERENCES), '/Map/entry[@key="forwardEndDate"]/value/Date')) AS "Delegate End Date"
FROM (
    SELECT * FROM sp.spt_identity 
    WHERE extended6='A' 
        AND PREFERENCES LIKE '%forward%'
) SI
INNER JOIN IDM.DW_IDENTITY_VERNOVA_V VI ON SI.NAME=VI.PERSON_NUM_SSO
ORDER by 'Delegate End Date' DESC

--IDM_USER_VW		
SELECT "PERSON_NUM_SSO", "FIRST_NAME", "LAST_NAME", "MIDDLE_NAME", "EMAIL_ADDRESS", "WORK_PHONE", "PERSON_STATUS", "PERSON_TYPE", "USER_ID", "US_PERSON_IND", "EC_CHECK_STATUS", "JOB_TITLE", "SSO_EXPIRATION_DATE", "LOCATION_NAME", "MANAGER_PERSON_NUM", "GET_SPONSOR", "CITY", "STATE", "COUNTRY", "DEEMED_US_EXPORT", "BU_NUMBER", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATE_DATE", "PERSON_INDICATOR", "JOB_CHANGE_IND", "TERMINATE_IND", "BU_CHANGE_IND", "JOB_FUNCTION", "EMAIL_DISPLAY_IND", "LDAP_GROUP", "NATIONALITY", "LDAP_DN", "NT_ID_CHANGE_IND", "GEAE_EMPLOYER_COMPANY", "GEAE_COMPANY_NAME", "GEAE_BUSINESS_PERSON_IND", "USER_GC_IND", "DEPARTMENT_NAME", "EMAIL_DISPLAY_NAME", "LEGAL_ENTITY_NAME", "EXEMPT_IND", "COMPANY_COUNTRY", "GRADE_BAND", "COST_CENTER_NUM", "DIVISION_NAME", "BUSINESS_SEGMENT", "KNOWN_AS", "HIRING_MANAGER_SSO", "ISRESOURCEPROVISIONED", "REACTIVATE_IND", "FEDERATED_PARTNERSHIP_CD", "WORK_DIALCOMM", "MAILSTOP", "ORGANIZATION_SEQ_ID", "SOURCE_APPL_INSTANCE", "REACTIVATED_BY", "REACTIVATION_DATE", "DEACTIVATED_BY", "DEACTIVATION_DATE", "PARENT_BU_NUMBER", "BUSINESS_SEGMENT_ID", "INDUSTRY_FOCUS_ID", "BUSINESS_SEGMENT_NAME", "INDUSTRY_FOCUS_NAME", "EFFECTIVE_DATE", "ACTIVE_SYNC_IND", "WORKER_TYPE", "GEMAILHOST", "GEHRJOBID", "GEHRLOCATIONID", "REITERATIVE_DPL_STATUS", "REITERATIVE_DPL_STATUS_DATE", "DOE", "DOC", "FEDERATED_ID", "ACQUISITION_CODE", "GENE", "JPNF", "CANDU", "EDOC", "EEXUS", "EEXCL", "MODI", "MODU", "NON_PERSONAL_ID_TYPE", "DIVISIONID", "COMPANYNAME", "GEHRINTEGRATEDORG", "GEHRASSIGNMENTSTATUS", "GEHRDISPOSITIONSTATUS", "GEHRBUSINESSDISPOSITIONDATE", "PRIOR_JOB_FUNCTION" 
FROM IDM_USER