SELECT PERSON_NUM_SSO AS "SSO"
	,TRIM (',' FROM FIRST_NAME || ' ' || MIDDLE_NAME  || ', ' || LAST_NAME) AS FULL_NAME
    ,EMAIL_DISPLAY_NAME
    ,EMAIL_ADDRESS 
    ,PERSON_STATUS
    ,PERSON_TYPE
    ,USER_ID
    ,JOB_TITLE
    ,JOB_FUNCTION
    ,SSO_EXPIRATION_DATE
    ,LAST_UPDATE_DATE
    ,EFFECTIVE_DATE
    ,INDUSTRY_FOCUS_NAME
    ,BUSINESS_SEGMENT
    ,COMPANYNAME
    ,DEPARTMENT_NAME
    ,PERSON_INDICATOR
    ,JOB_CHANGE_IND
    ,TERMINATE_IND
    ,BU_CHANGE_IND
    ,LDAP_GROUP
    ,LDAP_DN
    ,FEDERATED_ID
FROM IDM.IDM_USER_VW iuv
WHERE LAST_UPDATE_DATE > TIMESTAMP '2022-12-01 00:00:00.000000' 
	 AND PERSON_TYPE NOT LIKE 'FUNCTIONAL'
ORDER BY LAST_UPDATE_DATE DESC