-- Brief
SELECT 'IDM' AS object_type, TABLE_NAME
	FROM ALL_TABLES
	WHERE TABLE_NAME LIKE 'DW_IDM%' OR TABLE_NAME LIKE 'IDM%' OR TABLE_NAME LIKE '%IDENITY%' 	
UNION ALL
SELECT 'View' AS object_type, VIEW_NAME
	FROM ALL_VIEWS
	WHERE OWNER = 'IDM' 
		AND ( VIEW_NAME LIKE 'DW_IDM%' OR VIEW_NAME LIKE 'IDM%' OR VIEW_NAME LIKE '%ONEUI%' )
ORDER BY TABLE_NAME;

-- Tables
SELECT OWNER, 'TABLE' AS TYPE, TABLE_NAME AS NAME, NUM_ROWS, '' AS TEXT
	FROM ALL_TABLES
	WHERE TABLE_NAME LIKE 'DW_IDM%' OR TABLE_NAME LIKE 'IDM%'
	ORDER BY NAME

-- Views
SELECT OWNER, 'VIEW' AS TYPE, VIEW_NAME AS NAME, '' AS NUM_ROWS, TEXT 	
	FROM ALL_VIEWS
	WHERE OWNER = 'IDM' 
		AND ( 
			VIEW_NAME LIKE 'DW_IDM%' 
			OR VIEW_NAME LIKE 'DW_GRO%'
			OR VIEW_NAME LIKE 'DW_IDN%'
			OR VIEW_NAME LIKE 'DW_USE%'
			OR VIEW_NAME LIKE 'IDM_GRO%'
			OR VIEW_NAME LIKE 'IDM_IDN%'
			OR VIEW_NAME LIKE 'IDM_USE%'
			OR VIEW_NAME LIKE '%ONEUI%'
		)
	ORDER BY NAME


SELECT OWNER, 'TABLE' AS TYPE, TABLE_NAME AS NAME
	FROM ALL_TABLES
	WHERE TABLE_NAME LIKE 'DW_IDM%' OR TABLE_NAME = 'IDM_USER' OR TABLE_NAME LIKE '%IDENITY%'
UNION ALL
SELECT OWNER, 'VIEW' AS TYPE, VIEW_NAME AS NAME
	FROM ALL_VIEWS
	WHERE OWNER = 'IDM' 
		AND ( 
			VIEW_NAME LIKE 'DW_IDM%' 
			OR VIEW_NAME LIKE 'DW_GRO%'
			OR VIEW_NAME LIKE 'DW_IDN%'
			OR VIEW_NAME LIKE 'DW_USE%'
			OR VIEW_NAME LIKE 'IDM_GRO%'
			OR VIEW_NAME LIKE 'IDM_IDN%'
			OR VIEW_NAME LIKE 'IDM_USE%'
		)
	ORDER BY NAME;
	