SELECT * 
	FROM IDM.DW_IDM_GROUP
	WHERE GROUP_NAME LIKE '@GE %'
	ORDER BY GROUP_NAME ASC, GROUP_ID ASC

SELECT * FROM IDM.DW_IDM_GROUP_OWNER

SELECT * FROM IDM.DW_IDM_GROUP_MANAGER WHERE MANAGER LIKE 'cn=%' 

SELECT 
    G.GROUP_ID, 
    G.LDAP_HOST, 
    G.LDAP_OU, 
    G.GROUP_NAME, 
    REGEXP_SUBSTR(M.MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP, 
    G.PRIMARY_MANAGER_SSO AS GM_SSO, 
    GM.EMAIL_DISPLAY_NAME AS GM_EMAIL_DISP, 
    GM.PERSON_STATUS AS GM_STATUS, 
    GM.PERSON_TYPE AS GM_TYPE, 
    GM.JOB_TITLE AS GM_TITLE, 
    GM.JOB_FUNCTION AS GM_FUNC, 
    GM.INDUSTRY_FOCUS_NAME AS GM_BU, 
    GM.BUSINESS_SEGMENT AS GM_BU_SEG, 
    GM.DEPARTMENT_NAME AS GM_DEP, 
    GU.PERSON_NUM_SSO AS GU_SSO, 
    GU.EMAIL_DISPLAY_NAME AS GU_EMAIL_DISP, 
    GU.PERSON_STATUS AS GU_STATUS, 
    GU.PERSON_TYPE AS GU_TYPE, 
    GU.JOB_TITLE AS GU_TITLE, 
    GU.JOB_FUNCTION AS GU_FUNC, 
    GU.INDUSTRY_FOCUS_NAME AS GU_BU, 
    GU.BUSINESS_SEGMENT AS GU_BU_SEG, 
    GU.DEPARTMENT_NAME AS GU_DEP
FROM IDM.DW_IDM_GROUP G 
JOIN IDM.IDM_USER GM ON G.PRIMARY_MANAGER_SSO = GM.PERSON_NUM_SSO 
JOIN IDM.DW_IDM_GROUP_MEMBER M ON G.GROUP_ID = M.GROUP_ID 
JOIN IDM.IDM_USER GU ON M.MEMBER = GU.PERSON_NUM_SSO 
WHERE ( G.GROUP_NAME LIKE '@GE Cloud%' 
    -- Filter for Commercial & GovCloud DLs which ends to 12 Gits AWS Account ID 
    OR ( G.GROUP_NAME LIKE '@GE AWS_%' AND REGEXP_LIKE(G.GROUP_NAME, '[0-9]{12}$') ) 
    OR ( G.GROUP_NAME LIKE '@GE GOVAWS_%' AND REGEXP_LIKE(G.GROUP_NAME, '[0-9]{12}$') ) 
) AND ( G.GROUP_NAME LIKE '%141111311552' 
    OR G.GROUP_NAME LIKE '%188894168332' 
    OR G.GROUP_NAME LIKE '%207755114178' 
    OR G.GROUP_NAME LIKE '%264560008398' 
    OR G.GROUP_NAME LIKE '%277688789493' 
    OR G.GROUP_NAME LIKE '%376079469356' 
    OR G.GROUP_NAME LIKE '%432403552778' 
    OR G.GROUP_NAME LIKE '%504948279284' 
    OR G.GROUP_NAME LIKE '%556003251088' 
    OR G.GROUP_NAME LIKE '%589623221417' 
    OR G.GROUP_NAME LIKE '%736489861251' 
    OR G.GROUP_NAME LIKE '%737859062117' 
    OR G.GROUP_NAME LIKE '%020202940623' 
    OR G.GROUP_NAME LIKE '%147947222044' 
    OR G.GROUP_NAME LIKE '%330271845325' 
    OR G.GROUP_NAME LIKE '%610798319622' 
    OR G.GROUP_NAME LIKE '%715477192348' 
    OR G.GROUP_NAME LIKE '%896094434431' 
)
ORDER BY G.GROUP_NAME ASC, G.GROUP_ID ASC

SELECT 
	GROUP_ID,
	MEMBER,
	REGEXP_SUBSTR(MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP,
	FIRST_NAME,
	LAST_NAME,
	EMAIL_ADDRESS,
	MANAGER_PERSON_NUM,
	PERSON_STATUS
	FROM IDM.DW_IDM_GROUP_MEMBER
	WHERE REGEXP_SUBSTR(MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) IS NOT NULL --ROWNUM <= 200

SELECT GROUP_ID, MEMBER, REGEXP_SUBSTR(MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP 
	FROM IDM.DW_IDM_GROUP_MEMBER 
	WHERE MEMBER LIKE 'cn=g%' AND GROUP_ID IN ('g00021550'
		,'g02872755'
		,'g02890493'
		,'g03002020'
		,'g03023723'		
	)
	ORDER BY GROUP_ID 

SELECT * FROM IDM.IDM_USER iu 

SELECT 
    G.GROUP_ID, 
    G.LDAP_HOST, 
    G.LDAP_OU, 
    G.GROUP_NAME, 
    REGEXP_SUBSTR(M.MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP, 
    G.PRIMARY_MANAGER_SSO AS GM_SSO, 
    GM.EMAIL_DISPLAY_NAME AS GM_EMAIL_DISP, 
    GM.PERSON_STATUS AS GM_STATUS, 
    GM.PERSON_TYPE AS GM_TYPE, 
    GM.JOB_TITLE AS GM_TITLE, 
    GM.JOB_FUNCTION AS GM_FUNC, 
    GM.INDUSTRY_FOCUS_NAME AS GM_BU, 
    GM.BUSINESS_SEGMENT AS GM_BU_SEG, 
    GM.DEPARTMENT_NAME AS GM_DEP, 
    GU.PERSON_NUM_SSO AS GU_SSO, 
    GU.EMAIL_DISPLAY_NAME AS GU_EMAIL_DISP, 
    GU.PERSON_STATUS AS GU_STATUS, 
    GU.PERSON_TYPE AS GU_TYPE, 
    GU.JOB_TITLE AS GU_TITLE, 
    GU.JOB_FUNCTION AS GU_FUNC, 
    GU.INDUSTRY_FOCUS_NAME AS GU_BU, 
    GU.BUSINESS_SEGMENT AS GU_BU_SEG, 
    GU.DEPARTMENT_NAME AS GU_DEP
FROM IDM.DW_IDM_GROUP G 
JOIN IDM.IDM_USER GM ON G.PRIMARY_MANAGER_SSO = GM.PERSON_NUM_SSO 
JOIN IDM.DW_IDM_GROUP_MEMBER M ON G.GROUP_ID = M.GROUP_ID 
JOIN IDM.IDM_USER GU ON M.MEMBER = GU.PERSON_NUM_SSO 
WHERE ( G.GROUP_NAME LIKE '@GE Cloud%' 
    -- Filter for Commercial & GovCloud DLs which ends to 12 Gits AWS Account ID 
    OR ( G.GROUP_NAME LIKE '@GE AWS_%' AND REGEXP_LIKE(G.GROUP_NAME, '[0-9]{12}$') ) 
    OR ( G.GROUP_NAME LIKE '@GE GOVAWS_%' AND REGEXP_LIKE(G.GROUP_NAME, '[0-9]{12}$') ) 
) AND ( G.GROUP_NAME LIKE '%141111311552' 
    OR G.GROUP_NAME LIKE '%188894168332' 
    OR G.GROUP_NAME LIKE '%207755114178' 
    OR G.GROUP_NAME LIKE '%264560008398' 
    OR G.GROUP_NAME LIKE '%277688789493' 
    OR G.GROUP_NAME LIKE '%376079469356' 
    OR G.GROUP_NAME LIKE '%432403552778' 
    OR G.GROUP_NAME LIKE '%504948279284' 
    OR G.GROUP_NAME LIKE '%556003251088' 
    OR G.GROUP_NAME LIKE '%589623221417' 
    OR G.GROUP_NAME LIKE '%736489861251' 
    OR G.GROUP_NAME LIKE '%737859062117' 
    OR G.GROUP_NAME LIKE '%020202940623' 
    OR G.GROUP_NAME LIKE '%147947222044' 
    OR G.GROUP_NAME LIKE '%330271845325' 
    OR G.GROUP_NAME LIKE '%610798319622' 
    OR G.GROUP_NAME LIKE '%715477192348' 
    OR G.GROUP_NAME LIKE '%896094434431' 
) 
ORDER BY G.GROUP_NAME ASC, G.GROUP_ID ASC 

---TESTING----------------------------------
SELECT * FROM IDM.DW_IDENTITY 

SELECT CL."IDM_USER_CHANGE_EVENT_ID", CL."PERSON_NUM_SSO", CL."EVENT_TYPE", CL."PERSON_STATUS", CL."PERSON_STATUS_OLD", CL."GEHRLOCATIONID", CL."GEHRLOCATIONID_OLD", CL."INDUSTRY_FOCUS_ID", CL."INDUSTRY_FOCUS_ID_OLD", CL."GEHRJOBID", CL."GEHRJOBID_OLD", CL."MANAGER_PERSON_NUM", CL."MANAGER_PERSON_NUM_OLD", CL."NEW_MANAGER_DETAILS", CL."OLD_MANAGER_DETAILS", CL."FIRST_NAME", CL."FIRST_NAME_OLD", CL."LAST_NAME", CL."LAST_NAME_OLD", CL."BUSINESS_SEGMENT_ID", CL."BUSINESS_SEGMENT_ID_OLD", CL."BUSINESS_SEGMENT_NAME", CL."BUSINESS_SEGMENT_NAME_OLD", CL."CITY", CL."CITY_OLD", CL."COUNTRY", CL."COUNTRY_OLD", CL."DEPARTMENT_NAME", CL."DEPARTMENT_NAME_OLD", CL."DIVISIONID", CL."DIVISIONID_OLD", CL."DIVISION_NAME", CL."DIVISION_NAME_OLD", CL."EMAIL_ADDRESS", CL."EMAIL_ADDRESS_OLD", CL."EMAIL_DISPLAY_NAME", CL."EMAIL_DISPLAY_NAME_OLD", CL."BU_NUMBER", CL."BU_NUMBER_OLD", CL."GRADE_BAND", CL."GRADE_BAND_OLD", CL."INDUSTRY_FOCUS_NAME", CL."INDUSTRY_FOCUS_NAME_OLD", CL."JOB_TITLE", CL."JOB_TITLE_OLD", CL."PERSON_TYPE", CL."PERSON_TYPE_OLD", CL."SSO_EXPIRATION_DATE", CL."SSO_EXPIRATION_DATE_OLD", CL."STATE", CL."STATE_OLD", CL."WORKER_TYPE", CL."WORKER_TYPE_OLD", CL."WORK_PHONE", CL."WORK_PHONE_OLD", CL."PROCESS_STATUS", CL."EXTN1", CL."EXTN2", CL."CREATION_DATE", CL."LAST_UPDATE_DATE", CL."MIDDLE_NAME", CL."MIDDLE_NAME_OLD", CL."GEHRASSIGNMENTSTATUS", CL."GEHRASSIGNMENTSTATUS_OLD", CL."GEHRPOSITIONID", CL."GEHRPOSITIONID_OLD"
FROM IDM.IDM_USER_CHANGE_EVENT_LOG CL
INNER JOIN IDM.DW_IDENTITY I ON CL.PERSON_NUM_SSO = I.IDENTITY 
WHERE CL.LAST_UPDATE_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -2)

SELECT 
    G.GROUP_ID, 
    G.LDAP_HOST, 
    G.LDAP_OU, 
    G.GROUP_NAME, 
    REGEXP_SUBSTR(M.MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP, 
    G.PRIMARY_MANAGER_SSO AS GM_SSO, 
    GM.EMAIL_DISPLAY_NAME AS GM_EMAIL_DISP, 
    GM.PERSON_STATUS AS GM_STATUS, 
    GM.PERSON_TYPE AS GM_TYPE, 
    GM.JOB_TITLE AS GM_TITLE, 
    GM.JOB_FUNCTION AS GM_FUNC, 
    GM.INDUSTRY_FOCUS_NAME AS GM_BU, 
    GM.BUSINESS_SEGMENT AS GM_BU_SEG, 
    GM.DEPARTMENT_NAME AS GM_DEP, 
    GU.PERSON_NUM_SSO AS GU_SSO, 
    GU.EMAIL_DISPLAY_NAME AS GU_EMAIL_DISP, 
    GU.PERSON_STATUS AS GU_STATUS, 
    GU.PERSON_TYPE AS GU_TYPE, 
    GU.JOB_TITLE AS GU_TITLE, 
    GU.JOB_FUNCTION AS GU_FUNC, 
    GU.INDUSTRY_FOCUS_NAME AS GU_BU, 
    GU.BUSINESS_SEGMENT AS GU_BU_SEG, 
    GU.DEPARTMENT_NAME AS GU_DEP
FROM IDM.DW_IDM_GROUP G 
JOIN IDM.IDM_USER GM ON G.PRIMARY_MANAGER_SSO = GM.PERSON_NUM_SSO 
JOIN IDM.DW_IDM_GROUP_MEMBER M ON G.GROUP_ID = M.GROUP_ID 
JOIN IDM.IDM_USER GU ON M.MEMBER = GU.PERSON_NUM_SSO 
WHERE ( G.GROUP_NAME LIKE '@GE Cloud%' 
    -- Filter for Commercial & GovCloud DLs which ends to 12 Gits AWS Account ID 
    OR ( G.GROUP_NAME LIKE '@GE AWS_%' AND REGEXP_LIKE(G.GROUP_NAME, '[0-9]{12}$') ) 
    OR ( G.GROUP_NAME LIKE '@GE GOVAWS_%' AND REGEXP_LIKE(G.GROUP_NAME, '[0-9]{12}$') ) 
) AND ( G.GROUP_NAME LIKE '%141111311552' 
    OR G.GROUP_NAME LIKE '%188894168332' 
    OR G.GROUP_NAME LIKE '%207755114178' 
    OR G.GROUP_NAME LIKE '%264560008398' 
    OR G.GROUP_NAME LIKE '%277688789493' 
    OR G.GROUP_NAME LIKE '%376079469356' 
    OR G.GROUP_NAME LIKE '%432403552778' 
    OR G.GROUP_NAME LIKE '%504948279284' 
    OR G.GROUP_NAME LIKE '%556003251088' 
    OR G.GROUP_NAME LIKE '%589623221417' 
    OR G.GROUP_NAME LIKE '%736489861251' 
    OR G.GROUP_NAME LIKE '%737859062117' 
    OR G.GROUP_NAME LIKE '%020202940623' 
    OR G.GROUP_NAME LIKE '%147947222044' 
    OR G.GROUP_NAME LIKE '%330271845325' 
    OR G.GROUP_NAME LIKE '%610798319622' 
    OR G.GROUP_NAME LIKE '%715477192348' 
    OR G.GROUP_NAME LIKE '%896094434431' 
)
ORDER BY G.GROUP_NAME ASC, G.GROUP_ID ASC 



SELECT 
    G.GROUP_ID, 
    G.LDAP_HOST, 
    G.LDAP_OU, 
    G.GROUP_NAME, 
    M.MEMBER,
    REGEXP_SUBSTR(M.MEMBER, 'cn=([^,]+)', 1, 1, NULL, 1) AS NESTED_GROUP, 
    G.PRIMARY_MANAGER_SSO AS GM_SSO, 
    GM.EMAIL_DISPLAY_NAME AS GM_EMAIL_DISP, 
    GM.PERSON_STATUS AS GM_STATUS, 
    GM.PERSON_TYPE AS GM_TYPE, 
    GM.JOB_TITLE AS GM_TITLE, 
    GM.JOB_FUNCTION AS GM_FUNC, 
    GM.INDUSTRY_FOCUS_NAME AS GM_BU, 
    GM.BUSINESS_SEGMENT AS GM_BU_SEG, 
    GM.DEPARTMENT_NAME AS GM_DEP, 
    GU.PERSON_NUM_SSO AS GU_SSO, 
    GU.EMAIL_DISPLAY_NAME AS GU_EMAIL_DISP, 
    GU.PERSON_STATUS AS GU_STATUS, 
    GU.PERSON_TYPE AS GU_TYPE, 
    GU.JOB_TITLE AS GU_TITLE, 
    GU.JOB_FUNCTION AS GU_FUNC, 
    GU.INDUSTRY_FOCUS_NAME AS GU_BU, 
    GU.BUSINESS_SEGMENT AS GU_BU_SEG, 
    GU.DEPARTMENT_NAME AS GU_DEP
FROM IDM.DW_IDM_GROUP G 
JOIN IDM.IDM_USER GM ON G.PRIMARY_MANAGER_SSO = GM.PERSON_NUM_SSO 
JOIN IDM.DW_IDM_GROUP_MEMBER M ON G.GROUP_ID = M.GROUP_ID 
JOIN IDM.IDM_USER GU ON M.MEMBER = GU.PERSON_NUM_SSO 
WHERE G.GROUP_ID IN ('g02879368', 'g00918189')
ORDER BY G.GROUP_NAME ASC, G.GROUP_ID ASC 


SELECT * FROM IDM.DW_IDM_GROUP_MEMBER WHERE GROUP_ID IN ('g02879368', 'g00918189', 'g01311427') ORDER BY GROUP_ID ASC

SELECT * FROM IDM_ONEUI_SEARCH_CONTENT